"""SubAgent TypedDicts passed to ``create_deep_agent(subagents=...)``.

See components 09, 10, 13 for the domain partition.
"""

from __future__ import annotations

from strands_agents.subagents.production import (
    PRODUCTION_BOOTSTRAP_TOOLS,
    PRODUCTION_DISPATCH_TOOLS,
    PRODUCTION_FIX_BUDGET,
    PRODUCTION_RECOVERY_TOOLS,
    PRODUCTION_RETRY_BUDGET,
    PRODUCTION_SUBAGENT_DEFAULT_MODEL,
    PRODUCTION_SUBAGENT_MODEL_ENV,
    PRODUCTION_SUBAGENT_PROMPT,
    PRODUCTION_SUBAGENT_TOOL_NAMES,
    PRODUCTION_SUBAGENT_TOOLS,
    build_production_subagent,  # type: ignore[attr-defined]
)
from strands_agents.subagents.visual import (
    VISUAL_LOOP_BOOTSTRAP_TOOLS,
    VISUAL_LOOP_ITERATION_TOOLS,
    VISUAL_LOOP_MAX_ITERATIONS,
    VISUAL_LOOP_PASS_RATINGS,
    VISUAL_SUBAGENT_DEFAULT_MODEL,
    VISUAL_SUBAGENT_MODEL_ENV,
    VISUAL_SUBAGENT_PROMPT,
    VISUAL_SUBAGENT_TOOL_NAMES,
    VISUAL_SUBAGENT_TOOLS,
    build_visual_subagent,  # type: ignore[attr-defined]
)

__all__ = ['PRODUCTION_BOOTSTRAP_TOOLS', 'PRODUCTION_DISPATCH_TOOLS', 'PRODUCTION_FIX_BUDGET', 'PRODUCTION_RECOVERY_TOOLS', 'PRODUCTION_RETRY_BUDGET', 'PRODUCTION_SUBAGENT_DEFAULT_MODEL', 'PRODUCTION_SUBAGENT_MODEL_ENV', 'PRODUCTION_SUBAGENT_PROMPT', 'PRODUCTION_SUBAGENT_TOOLS', 'PRODUCTION_SUBAGENT_TOOL_NAMES', 'VISUAL_LOOP_BOOTSTRAP_TOOLS', 'VISUAL_LOOP_ITERATION_TOOLS', 'VISUAL_LOOP_MAX_ITERATIONS', 'VISUAL_LOOP_PASS_RATINGS', 'VISUAL_SUBAGENT_DEFAULT_MODEL', 'VISUAL_SUBAGENT_MODEL_ENV', 'VISUAL_SUBAGENT_PROMPT', 'VISUAL_SUBAGENT_TOOLS', 'VISUAL_SUBAGENT_TOOL_NAMES', 'annotations', 'build_production_subagent', 'build_visual_subagent']
