"use client";

import { useEffect, useState, useCallback } from "react";
import type { VisualConcept } from "@/lib/types";

const BACKEND_URL =
  process.env.NEXT_PUBLIC_BACKEND_URL || "http://localhost:8000";

/**
 * Gate 2: Prompt Reviewer — visual prompts + LoRA review.
 *
 * Displays the 6-layer cinematic prompts and LoRA selections
 * generated by the Visual Director. User can approve, reject,
 * or request modifications.
 *
 * Data source: GET /agui/visual-concepts (reads video status files on disk)
 */
export function PromptReviewer() {
  const [concepts, setConcepts] = useState<VisualConcept[]>([]);
  const [visualStyle, setVisualStyle] = useState<Record<string, string>>({});

  // Poll AG-UI /visual-concepts endpoint
  const fetchConcepts = useCallback(async () => {
    try {
      const res = await fetch(`${BACKEND_URL}/agui/visual-concepts`);
      const data = await res.json();
      if (data.concepts && data.concepts.length > 0) {
        setConcepts(data.concepts);
      }
      if (data.visual_style) {
        setVisualStyle(data.visual_style);
      }
    } catch {
      // ignore fetch errors
    }
  }, []);

  useEffect(() => {
    fetchConcepts();
    const interval = setInterval(fetchConcepts, 5000);
    return () => clearInterval(interval);
  }, [fetchConcepts]);

  if (concepts.length === 0) {
    return (
      <div className="flex items-center justify-center h-64">
        <div className="text-center">
          <div className="text-xl mb-2">No Visual Concepts Yet</div>
          <div className="text-pipeline-muted">
            Visual concepts will appear after the visual director completes
          </div>
        </div>
      </div>
    );
  }

  return (
    <div className="space-y-6">
      {/* Visual style summary */}
      {visualStyle.style && (
        <div className="bg-pipeline-card rounded-lg p-4">
          <h3 className="text-sm font-semibold text-pipeline-accent mb-2">
            Visual Style
          </h3>
          <div className="text-sm text-pipeline-muted">{visualStyle.style}</div>
          {visualStyle.palette && (
            <div className="text-xs text-pipeline-muted mt-1">
              Palette: {visualStyle.palette}
            </div>
          )}
        </div>
      )}

      <div className="flex items-center justify-between">
        <h2 className="text-lg font-semibold text-pipeline-accent">
          Visual Prompts: {concepts.length} Phrases
        </h2>
        <div className="flex gap-2">
          <button className="px-4 py-2 bg-green-700 text-white rounded-md text-sm hover:bg-green-600">
            Approve All
          </button>
        </div>
      </div>

      {concepts.map((concept, idx) => (
        <div key={idx} className="bg-pipeline-card rounded-lg p-4">
          <div className="flex items-center justify-between mb-2">
            <h3 className="font-semibold">
              Scene {concept.scene_num}, Phrase {concept.phrase_idx}
            </h3>
            <span className="text-sm text-pipeline-muted">
              {(concept as Record<string, unknown>).quality === "acceptable" ? (
                <span className="text-green-400">QA: pass</span>
              ) : (concept as Record<string, unknown>).quality === "unknown" ? (
                <span className="text-yellow-400">QA: pending</span>
              ) : (
                <span className="text-red-400">
                  QA: {String((concept as Record<string, unknown>).quality || "pending")}
                </span>
              )}
            </span>
          </div>

          <div className="mb-3 p-3 bg-pipeline-bg rounded text-sm font-mono">
            {concept.prompt}
          </div>

          <div className="grid grid-cols-3 gap-2 text-sm">
            <div>
              <span className="text-pipeline-muted">LoRA: </span>
              <span className="text-pipeline-accent">
                {concept.lora_id || "default"}
              </span>
            </div>
            <div>
              <span className="text-pipeline-muted">Camera: </span>
              {concept.camera_style}
            </div>
            <div>
              <span className="text-pipeline-muted">Mood: </span>
              {concept.mood}
            </div>
          </div>

          <div className="mt-2 flex gap-2">
            <button className="px-3 py-1 bg-green-800 text-green-200 rounded text-xs hover:bg-green-700">
              Approve
            </button>
            <button className="px-3 py-1 bg-red-800 text-red-200 rounded text-xs hover:bg-red-700">
              Reject
            </button>
          </div>
        </div>
      ))}
    </div>
  );
}
