"use client";

import { useEffect, useState, useCallback } from "react";
import type { VisualConcept } from "@/lib/types";

const BACKEND_URL =
  process.env.NEXT_PUBLIC_BACKEND_URL || "http://localhost:8000";

/**
 * Gate 2: Prompt Reviewer — visual prompts + LoRA review.
 *
 * Displays the 6-layer cinematic prompts and LoRA selections
 * generated by the Visual Director. User can approve, reject,
 * or request modifications with free-text feedback.
 *
 * Data source: GET /agui/visual-concepts (reads video status files on disk)
 */
export function PromptReviewer() {
  const [mounted, setMounted] = useState(false);
  const [concepts, setConcepts] = useState<VisualConcept[]>([]);
  const [visualStyle, setVisualStyle] = useState<Record<string, string>>({});
  const [gateBlocked, setGateBlocked] = useState(false);
  const [gateMessage, setGateMessage] = useState("");
  const [approved, setApproved] = useState(false);
  const [approving, setApproving] = useState(false);

  // Feedback modal state
  const [feedbackModal, setFeedbackModal] = useState<{
    open: boolean;
    type: "approve" | "reject";
    conceptIdx: number;
    comment: string;
  }>({ open: false, type: "approve", conceptIdx: -1, comment: "" });
  const [feedbackSent, setFeedbackSent] = useState<Record<number, string>>({});

  // Poll AG-UI /visual-concepts endpoint
  const fetchConcepts = useCallback(async () => {
    try {
      const res = await fetch(`${BACKEND_URL}/agui/visual-concepts`);
      const data = await res.json();
      if (data.gate?.blocked) {
        setGateBlocked(true);
        setGateMessage(data.gate.message || "Waiting for previous stage approval");
        return;
      }
      setGateBlocked(false);
      if (data.concepts && data.concepts.length > 0) {
        setConcepts(data.concepts);
      }
      if (data.visual_style) {
        setVisualStyle(data.visual_style);
      }
    } catch {
      // ignore fetch errors
    }
  }, []);

  // Check approval state
  const fetchApprovalState = useCallback(async () => {
    try {
      const res = await fetch(`${BACKEND_URL}/agui/approval-state`);
      const data = await res.json();
      if (data.state?.prompts?.approved) {
        setApproved(true);
      }
    } catch {
      // ignore
    }
  }, []);

  useEffect(() => {
    setMounted(true);
    fetchConcepts();
    fetchApprovalState();
    const interval = setInterval(() => {
      fetchConcepts();
      fetchApprovalState();
    }, 5000);
    return () => clearInterval(interval);
  }, [fetchConcepts, fetchApprovalState]);

  const handleApproveAll = async () => {
    setApproving(true);
    try {
      const res = await fetch(`${BACKEND_URL}/agui/approve`, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ stage: "prompts" }),
      });
      if (res.ok) {
        setApproved(true);
      }
    } catch {
      // ignore
    } finally {
      setApproving(false);
    }
  };

  const openFeedbackModal = (type: "approve" | "reject", conceptIdx: number) => {
    setFeedbackModal({ open: true, type, conceptIdx, comment: "" });
  };

  const submitFeedback = async () => {
    const { type, conceptIdx, comment } = feedbackModal;
    const concept = concepts[conceptIdx];
    if (!concept) return;
    try {
      await fetch(`${BACKEND_URL}/agui/feedback`, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          feedback_type: type,
          artifact_id: `prompt_s${concept.scene_num}_p${concept.phrase_idx}`,
          scene_num: concept.scene_num,
          comment,
        }),
      });
      setFeedbackSent((prev) => ({ ...prev, [conceptIdx]: type }));
    } catch {
      // ignore
    }
    setFeedbackModal({ open: false, type: "approve", conceptIdx: -1, comment: "" });
  };

  if (!mounted) {
    return (
      <div className="flex items-center justify-center h-64">
        <div className="text-center">
          <div className="text-xl mb-2">Loading...</div>
        </div>
      </div>
    );
  }

  if (gateBlocked) {
    return (
      <div className="flex items-center justify-center h-64">
        <div className="text-center">
          <div className="text-xl mb-2 text-yellow-400">Waiting for Approval</div>
          <div className="text-pipeline-muted">{gateMessage}</div>
          <div className="mt-4 text-sm text-pipeline-muted">
            Approve the scenario on the Scenario Editor tab to unlock this stage
          </div>
        </div>
      </div>
    );
  }

  if (concepts.length === 0) {
    return (
      <div className="flex items-center justify-center h-64">
        <div className="text-center">
          <div className="text-xl mb-2">No Visual Concepts Yet</div>
          <div className="text-pipeline-muted">
            Visual concepts will appear after the visual director completes
          </div>
        </div>
      </div>
    );
  }

  return (
    <div className="space-y-6">
      {/* Feedback Modal */}
      {feedbackModal.open && (
        <div className="fixed inset-0 bg-black/60 flex items-center justify-center z-50">
          <div className="bg-pipeline-card border border-gray-600 rounded-lg p-6 max-w-md w-full mx-4">
            <h3 className="text-lg font-semibold mb-3">
              {feedbackModal.type === "approve" ? (
                <span className="text-green-400">Approve Prompt</span>
              ) : (
                <span className="text-red-400">Reject Prompt</span>
              )}
            </h3>
            <p className="text-sm text-pipeline-muted mb-3">
              Scene {concepts[feedbackModal.conceptIdx]?.scene_num}, Phrase{" "}
              {concepts[feedbackModal.conceptIdx]?.phrase_idx}
            </p>
            <textarea
              className="w-full bg-pipeline-bg border border-gray-600 rounded p-3 text-sm text-white placeholder-gray-500 focus:border-pipeline-accent focus:outline-none"
              rows={4}
              placeholder={
                feedbackModal.type === "approve"
                  ? "Why are you approving? (optional — e.g., good composition, strong mood)"
                  : "Why are you rejecting? (required — e.g., wrong mood, too literal, missing symbolism)"
              }
              value={feedbackModal.comment}
              onChange={(e) =>
                setFeedbackModal((prev) => ({ ...prev, comment: e.target.value }))
              }
              autoFocus
            />
            <div className="flex gap-3 mt-4">
              <button
                onClick={submitFeedback}
                disabled={feedbackModal.type === "reject" && !feedbackModal.comment.trim()}
                className={`flex-1 py-2 rounded text-sm font-medium transition-colors disabled:opacity-40 ${
                  feedbackModal.type === "approve"
                    ? "bg-green-700 hover:bg-green-600 text-white"
                    : "bg-red-700 hover:bg-red-600 text-white"
                }`}
              >
                Submit {feedbackModal.type === "approve" ? "Approval" : "Rejection"}
              </button>
              <button
                onClick={() =>
                  setFeedbackModal({ open: false, type: "approve", conceptIdx: -1, comment: "" })
                }
                className="px-4 py-2 bg-gray-700 hover:bg-gray-600 text-white rounded text-sm transition-colors"
              >
                Cancel
              </button>
            </div>
          </div>
        </div>
      )}

      {/* Visual style summary */}
      {visualStyle.style && (
        <div className="bg-pipeline-card rounded-lg p-4">
          <h3 className="text-sm font-semibold text-pipeline-accent mb-2">
            Visual Style
          </h3>
          <div className="text-sm text-pipeline-muted">{visualStyle.style}</div>
          {visualStyle.palette && (
            <div className="text-xs text-pipeline-muted mt-1">
              Palette: {visualStyle.palette}
            </div>
          )}
        </div>
      )}

      <div className="flex items-center justify-between">
        <h2 className="text-lg font-semibold text-pipeline-accent">
          Visual Prompts: {concepts.length} Phrases
        </h2>
        <div className="flex gap-2">
          {approved ? (
            <span className="px-4 py-2 bg-green-900 text-green-300 rounded-md text-sm">
              Prompts Approved
            </span>
          ) : (
            <button
              onClick={handleApproveAll}
              disabled={approving}
              className="px-4 py-2 bg-green-700 text-white rounded-md text-sm hover:bg-green-600 disabled:opacity-50"
            >
              {approving ? "Approving..." : "Approve All"}
            </button>
          )}
        </div>
      </div>

      {concepts.map((concept, idx) => (
        <div key={idx} className="bg-pipeline-card rounded-lg p-4">
          <div className="flex items-center justify-between mb-2">
            <h3 className="font-semibold">
              Scene {concept.scene_num}, Phrase {concept.phrase_idx}
            </h3>
            <span className="text-sm text-pipeline-muted">
              {concept.quality === "acceptable" ? (
                <span className="text-green-400">QA: pass</span>
              ) : concept.quality === "unknown" ? (
                <span className="text-yellow-400">QA: pending</span>
              ) : (
                <span className="text-red-400">
                  QA: {concept.quality || "pending"}
                </span>
              )}
            </span>
          </div>

          <div className="mb-3 p-3 bg-pipeline-bg rounded text-sm font-mono whitespace-pre-wrap">
            {concept.prompt}
          </div>

          {/* Prompt Reasoning */}
          {concept.prompt_reasoning && (
            <div className="mb-3 p-3 bg-blue-900/20 border border-blue-800/40 rounded text-sm">
              <span className="text-blue-400 font-medium text-xs uppercase tracking-wide">
                Reasoning:{" "}
              </span>
              <span className="text-blue-200">{concept.prompt_reasoning}</span>
            </div>
          )}

          <div className="grid grid-cols-3 gap-2 text-sm">
            <div>
              <span className="text-pipeline-muted">LoRA: </span>
              <span className="text-pipeline-accent">
                {concept.lora_id || "default"}
              </span>
            </div>
            <div>
              <span className="text-pipeline-muted">Camera: </span>
              {concept.camera_style}
            </div>
            <div>
              <span className="text-pipeline-muted">Mood: </span>
              {concept.mood}
            </div>
          </div>

          <div className="mt-2 flex gap-2 items-center">
            {feedbackSent[idx] ? (
              <span
                className={`text-xs px-3 py-1 rounded ${
                  feedbackSent[idx] === "approve"
                    ? "bg-green-900 text-green-300"
                    : "bg-red-900 text-red-300"
                }`}
              >
                {feedbackSent[idx] === "approve" ? "Approved" : "Rejected"} — feedback sent
              </span>
            ) : (
              <>
                <button
                  onClick={() => openFeedbackModal("approve", idx)}
                  className="px-3 py-1 bg-green-800 text-green-200 rounded text-xs hover:bg-green-700 transition-colors"
                >
                  Approve
                </button>
                <button
                  onClick={() => openFeedbackModal("reject", idx)}
                  className="px-3 py-1 bg-red-800 text-red-200 rounded text-xs hover:bg-red-700 transition-colors"
                >
                  Reject
                </button>
              </>
            )}
          </div>
        </div>
      ))}
    </div>
  );
}
