"use client";

import { useCopilotReadable } from "@copilotkit/react-core";
import { useEffect, useState, useCallback } from "react";
import type { Scene, VoiceBlock } from "@/lib/types";

const BACKEND_URL =
  process.env.NEXT_PUBLIC_BACKEND_URL || "http://localhost:8000";

/**
 * Gate 1: Scenario Editor — editable script review.
 *
 * Displays generated scenes with V1/V2/V3 voice blocks.
 * User can edit text, approve, or request regeneration.
 *
 * Data source: GET /agui/scenes (reads _scenes_backup.json on disk)
 */
export function ScenarioEditor() {
  const [scenes, setScenes] = useState<Scene[]>([]);
  const [editingScene, setEditingScene] = useState<number | null>(null);
  const [approved, setApproved] = useState(false);
  const [approving, setApproving] = useState(false);

  // Regeneration modal state
  const [regenModal, setRegenModal] = useState<{
    open: boolean;
    comment: string;
  }>({ open: false, comment: "" });
  const [regenSent, setRegenSent] = useState(false);

  // Make scenes readable by CopilotKit
  useCopilotReadable({
    description: "The documentary scenes generated by the scenario director",
    value: JSON.stringify(scenes),
  });

  // Poll AG-UI /scenes endpoint
  const fetchScenes = useCallback(async () => {
    try {
      const res = await fetch(`${BACKEND_URL}/agui/scenes`);
      const data = await res.json();
      if (data.scenes && data.scenes.length > 0) {
        setScenes(data.scenes);
      }
    } catch {
      // ignore fetch errors
    }
  }, []);

  // Check approval state
  const fetchApprovalState = useCallback(async () => {
    try {
      const res = await fetch(`${BACKEND_URL}/agui/approval-state`);
      const data = await res.json();
      if (data.state?.scenario?.approved) {
        setApproved(true);
      }
    } catch {
      // ignore
    }
  }, []);

  useEffect(() => {
    fetchScenes();
    fetchApprovalState();
    const interval = setInterval(() => {
      fetchScenes();
      fetchApprovalState();
    }, 5000);
    return () => clearInterval(interval);
  }, [fetchScenes, fetchApprovalState]);

  const handleApproveAll = async () => {
    setApproving(true);
    try {
      const res = await fetch(`${BACKEND_URL}/agui/approve`, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ stage: "scenario" }),
      });
      if (res.ok) {
        setApproved(true);
      }
    } catch {
      // ignore
    } finally {
      setApproving(false);
    }
  };

  const submitRegeneration = async () => {
    try {
      await fetch(`${BACKEND_URL}/agui/regenerate`, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          level: "style",
          comment: regenModal.comment,
        }),
      });
      setRegenSent(true);
    } catch {
      // ignore
    }
    setRegenModal({ open: false, comment: "" });
  };

  if (scenes.length === 0) {
    return (
      <div className="flex items-center justify-center h-64">
        <div className="text-center">
          <div className="text-xl mb-2">No Scenes Yet</div>
          <div className="text-pipeline-muted">
            The scenario director will generate scenes after you provide a topic
          </div>
        </div>
      </div>
    );
  }

  return (
    <div className="space-y-6">
      {/* Regeneration Modal */}
      {regenModal.open && (
        <div className="fixed inset-0 bg-black/60 flex items-center justify-center z-50">
          <div className="bg-pipeline-card border border-gray-600 rounded-lg p-6 max-w-md w-full mx-4">
            <h3 className="text-lg font-semibold mb-3 text-pipeline-accent">
              Regenerate Scenario
            </h3>
            <p className="text-sm text-pipeline-muted mb-3">
              Explain what you want changed so the AI can regenerate with your guidance.
            </p>
            <textarea
              className="w-full bg-pipeline-bg border border-gray-600 rounded p-3 text-sm text-white placeholder-gray-500 focus:border-pipeline-accent focus:outline-none"
              rows={4}
              placeholder="Why regenerate? (e.g., too dry, needs more conflict, wrong tone for audience, missing key angle...)"
              value={regenModal.comment}
              onChange={(e) =>
                setRegenModal((prev) => ({ ...prev, comment: e.target.value }))
              }
              autoFocus
            />
            <div className="flex gap-3 mt-4">
              <button
                onClick={submitRegeneration}
                disabled={!regenModal.comment.trim()}
                className="flex-1 py-2 bg-pipeline-accent hover:bg-red-500 text-white rounded text-sm font-medium transition-colors disabled:opacity-40"
              >
                Regenerate with Feedback
              </button>
              <button
                onClick={() => setRegenModal({ open: false, comment: "" })}
                className="px-4 py-2 bg-gray-700 hover:bg-gray-600 text-white rounded text-sm transition-colors"
              >
                Cancel
              </button>
            </div>
          </div>
        </div>
      )}

      <div className="flex items-center justify-between">
        <h2 className="text-lg font-semibold text-pipeline-accent">
          Scenario: {scenes.length} Scenes
        </h2>
        <div className="flex gap-2">
          {approved ? (
            <span className="px-4 py-2 bg-green-900 text-green-300 rounded-md text-sm">
              Scenario Approved
            </span>
          ) : (
            <button
              onClick={handleApproveAll}
              disabled={approving}
              className="px-4 py-2 bg-green-700 text-white rounded-md text-sm hover:bg-green-600 disabled:opacity-50"
            >
              {approving ? "Approving..." : "Approve All"}
            </button>
          )}
          {regenSent ? (
            <span className="px-4 py-2 bg-yellow-900 text-yellow-300 rounded-md text-sm">
              Regeneration Queued
            </span>
          ) : (
            <button
              onClick={() => setRegenModal({ open: true, comment: "" })}
              className="px-4 py-2 bg-pipeline-accent text-white rounded-md text-sm hover:bg-red-500 transition-colors"
            >
              Regenerate
            </button>
          )}
        </div>
      </div>

      {scenes.map((scene) => (
        <div key={scene.scene_num} className="bg-pipeline-card rounded-lg p-4">
          <div className="flex items-center justify-between mb-3">
            <h3 className="font-semibold">
              Scene {scene.scene_num}: {scene.title}
            </h3>
            <span className="text-sm text-pipeline-muted">
              {scene.duration_sec}s
            </span>
          </div>

          {scene.dopamine_hook && (
            <div className="mb-3 p-2 bg-yellow-900/30 rounded text-sm">
              <span className="font-medium text-yellow-400">Hook: </span>
              {scene.dopamine_hook}
            </div>
          )}

          <div className="space-y-2">
            {scene.voices.map((voice) => (
              <VoiceBlockDisplay
                key={voice.voice}
                voice={voice}
                isEditing={editingScene === scene.scene_num}
              />
            ))}
          </div>

          <div className="mt-3 text-sm text-pipeline-muted">
            Visual: {scene.visual_notes}
          </div>
        </div>
      ))}
    </div>
  );
}

function VoiceBlockDisplay({
  voice,
  isEditing,
}: {
  voice: VoiceBlock;
  isEditing: boolean;
}) {
  const voiceColors: Record<string, string> = {
    V1: "border-red-500",
    V2: "border-blue-500",
    V3: "border-green-500",
  };
  const voiceLabels: Record<string, string> = {
    V1: "The Hook",
    V2: "The Expert",
    V3: "The Storyteller",
  };

  return (
    <div
      className={`border-l-4 ${voiceColors[voice.voice] || "border-gray-500"} pl-3 py-1`}
    >
      <div className="text-xs font-medium text-pipeline-muted mb-1">
        {voice.voice} — {voiceLabels[voice.voice] || voice.voice} ({voice.tone})
      </div>
      {isEditing ? (
        <textarea
          className="w-full bg-pipeline-bg border border-pipeline-blue rounded p-2 text-sm"
          defaultValue={voice.text}
          rows={3}
        />
      ) : (
        <div className="text-sm">{voice.text}</div>
      )}
    </div>
  );
}
