"use client";

import { useCopilotReadable } from "@copilotkit/react-core";
import { useState } from "react";
import type { Scene, VoiceBlock } from "@/lib/types";

/**
 * Gate 1: Scenario Editor — editable script review.
 *
 * Displays generated scenes with V1/V2/V3 voice blocks.
 * User can edit text, approve, or request regeneration.
 */
export function ScenarioEditor() {
  const [scenes, setScenes] = useState<Scene[]>([]);
  const [editingScene, setEditingScene] = useState<number | null>(null);

  // Make scenes readable by CopilotKit
  useCopilotReadable({
    description: "The documentary scenes generated by the scenario director",
    value: JSON.stringify(scenes),
  });

  if (scenes.length === 0) {
    return (
      <div className="flex items-center justify-center h-64">
        <div className="text-center">
          <div className="text-xl mb-2">No Scenes Yet</div>
          <div className="text-pipeline-muted">
            The scenario director will generate scenes after you provide a topic
          </div>
        </div>
      </div>
    );
  }

  return (
    <div className="space-y-6">
      <div className="flex items-center justify-between">
        <h2 className="text-lg font-semibold text-pipeline-accent">
          Scenario: {scenes.length} Scenes
        </h2>
        <div className="flex gap-2">
          <button className="px-4 py-2 bg-green-700 text-white rounded-md text-sm hover:bg-green-600">
            Approve All
          </button>
          <button className="px-4 py-2 bg-pipeline-accent text-white rounded-md text-sm hover:bg-red-500">
            Regenerate
          </button>
        </div>
      </div>

      {scenes.map((scene) => (
        <div key={scene.scene_num} className="bg-pipeline-card rounded-lg p-4">
          <div className="flex items-center justify-between mb-3">
            <h3 className="font-semibold">
              Scene {scene.scene_num}: {scene.title}
            </h3>
            <span className="text-sm text-pipeline-muted">
              {scene.duration_sec}s
            </span>
          </div>

          {scene.dopamine_hook && (
            <div className="mb-3 p-2 bg-yellow-900/30 rounded text-sm">
              <span className="font-medium text-yellow-400">Hook: </span>
              {scene.dopamine_hook}
            </div>
          )}

          <div className="space-y-2">
            {scene.voices.map((voice) => (
              <VoiceBlockDisplay
                key={voice.voice}
                voice={voice}
                isEditing={editingScene === scene.scene_num}
              />
            ))}
          </div>

          <div className="mt-3 text-sm text-pipeline-muted">
            Visual: {scene.visual_notes}
          </div>
        </div>
      ))}
    </div>
  );
}

function VoiceBlockDisplay({
  voice,
  isEditing,
}: {
  voice: VoiceBlock;
  isEditing: boolean;
}) {
  const voiceColors: Record<string, string> = {
    V1: "border-red-500",
    V2: "border-blue-500",
    V3: "border-green-500",
  };
  const voiceLabels: Record<string, string> = {
    V1: "The Hook",
    V2: "The Expert",
    V3: "The Storyteller",
  };

  return (
    <div
      className={`border-l-4 ${voiceColors[voice.voice] || "border-gray-500"} pl-3 py-1`}
    >
      <div className="text-xs font-medium text-pipeline-muted mb-1">
        {voice.voice} — {voiceLabels[voice.voice] || voice.voice} ({voice.tone})
      </div>
      {isEditing ? (
        <textarea
          className="w-full bg-pipeline-bg border border-pipeline-blue rounded p-2 text-sm"
          defaultValue={voice.text}
          rows={3}
        />
      ) : (
        <div className="text-sm">{voice.text}</div>
      )}
    </div>
  );
}
