#!/usr/bin/env python3
"""
Video Quality Checker — Qwen3-Omni-Thinking on Dedicated VM
=============================================================
Assesses each generated video clip using Qwen3-Omni-30B-A3B-Thinking for
AI artifact detection across 6 quality dimensions.

Designed to run on a SEPARATE Vast.ai VM from the LTX-2.3 generation VM:
  - VM-A: LTX-2.3 generates clips, uploads to B2
  - VM-B: Qwen3-Omni watches each clip, scores quality, flags failures
  - OTIO file is the coordination mechanism

Quality dimensions:
  1. ANATOMICAL — body proportions, finger count, face stability
  2. TEMPORAL   — object consistency across frames, morphing
  3. MOTION     — physical plausibility, impossible physics
  4. TEXTURE    — surface stability, flickering, shimmering
  5. SPATIAL    — 3D coherence, impossible perspectives
  6. CINEMATIC  — overall documentary plausibility

Usage (standalone on QC VM):
  python3 -m pipeline.quality_checker \\
      --otio production/timeline.otio \\
      --clips-dir /workspace/outputs \\
      --output production/quality_report.json

Usage (from orchestrator):
  python3 -m pipeline.orchestrator --phase quality \\
      --otio production/timeline.otio --output-dir production
"""

import argparse
import json
import logging
import os
import re
import time
from datetime import datetime, timezone

logging.basicConfig(level=logging.INFO, format="%(asctime)s | %(message)s")
log = logging.getLogger(__name__)

# ------------------------------------------------------------------
# Model configuration
# ------------------------------------------------------------------
QWEN_MODEL_ID = "Qwen/Qwen3-Omni-30B-A3B-Thinking"
QWEN_LOCAL_PATH = "/workspace/models/qwen3-omni-30b-a3b-thinking"

PASS_THRESHOLD = 0.6
MARGINAL_THRESHOLD = 0.4

QUALITY_CATEGORIES = [
    "anatomical", "temporal", "motion", "texture", "spatial", "cinematic"
]

# ------------------------------------------------------------------
# Prompts
# ------------------------------------------------------------------
SYSTEM_PROMPT = (
    "You are a video quality control specialist for AI-generated documentary footage. "
    "Watch the video carefully and think step by step about any visual quality issues. "
    "Be specific and objective — describe exactly what you see frame by frame."
)

ASSESSMENT_PROMPT_TEMPLATE = '''Watch this video clip carefully. It was generated by an AI video model (LTX-2.3) for a documentary.

The intended visual description was: "{prompt_text}"
Target duration: {duration}s

Think step by step about each quality dimension, then provide your assessment.

Assess for these specific AI-generation artifacts:

1. ANATOMICAL: Human body proportions, finger count, face stability, limb articulation
2. TEMPORAL: Object shape/size/position consistency across frames, morphing, appearing/disappearing objects
3. MOTION: Physical plausibility of movement, impossible physics, teleportation, jitter
4. TEXTURE: Surface material consistency, flickering, shimmering, texture swimming
5. SPATIAL: 3D space coherence, impossible perspectives, depth errors, clipping
6. CINEMATIC: Does this pass as real documentary footage to a casual viewer?

After your analysis, provide your final assessment in EXACTLY this format:

ANATOMICAL: [PASS/FAIL] — [one line description]
TEMPORAL: [PASS/FAIL] — [one line description]
MOTION: [PASS/FAIL] — [one line description]
TEXTURE: [PASS/FAIL] — [one line description]
SPATIAL: [PASS/FAIL] — [one line description]
CINEMATIC: [PASS/FAIL] — [one line description]
SCORE: [0.0-1.0]
VERDICT: [PASS/MARGINAL/FAIL]
ISSUES: [comma-separated list of specific issues, or "none"]
'''

# ------------------------------------------------------------------
# Negative prompt enhancements per failure category
# ------------------------------------------------------------------
REGENERATION_NEGATIVE_PROMPTS = {
    "anatomical": "deformed hands, extra fingers, distorted face, mutated limbs",
    "temporal": "morphing objects, flickering shapes, inconsistent forms",
    "motion": "impossible physics, teleporting objects, jerky motion",
    "texture": "flickering textures, shimmering surfaces, unstable materials",
}

# ------------------------------------------------------------------
# Conditional imports — Qwen3-Omni only available on QC VM
# ------------------------------------------------------------------
try:
    from transformers import Qwen3OmniMoeForConditionalGeneration, Qwen3OmniMoeProcessor
    from qwen_omni_utils import process_mm_info
    QWEN_AVAILABLE = True
except ImportError:
    QWEN_AVAILABLE = False


class VideoQualityChecker:
    """
    Assesses video quality using Qwen3-Omni-30B-A3B-Thinking.

    The model loads ONCE and processes all clips sequentially.
    Results are written back to OTIO metadata and a quality report JSON.
    """

    def __init__(self, model_path=None):
        self.model_path = model_path or QWEN_LOCAL_PATH
        self.model = None
        self.processor = None

    def load_model(self):
        """Load Qwen3-Omni-Thinking model (one-time)."""
        if not QWEN_AVAILABLE:
            raise RuntimeError(
                "Qwen3-Omni dependencies not installed. "
                "Install: pip install transformers accelerate qwen-omni-utils[decord] flash-attn torch"
            )

        import torch

        model_path = self.model_path
        if not os.path.exists(model_path):
            log.info(f"Local model not found at {model_path}, falling back to HuggingFace: {QWEN_MODEL_ID}")
            model_path = QWEN_MODEL_ID

        log.info(f"Loading Qwen3-Omni-Thinking from {model_path}...")
        t0 = time.time()

        self.model = Qwen3OmniMoeForConditionalGeneration.from_pretrained(
            model_path,
            dtype=torch.bfloat16,
            device_map="auto",
            attn_implementation="flash_attention_2",
            enable_audio_output=False,
        )
        self.model.disable_talker()
        self.processor = Qwen3OmniMoeProcessor.from_pretrained(model_path)

        log.info(f"Model loaded in {time.time() - t0:.1f}s")

    def assess_clip(self, video_path, prompt_text, target_duration_sec):
        """
        Assess a single video clip for quality.

        Returns dict with quality_score, verdict, categories, issues, thinking_trace.
        """
        if self.model is None:
            raise RuntimeError("Model not loaded. Call load_model() first.")

        conversation = [
            {"role": "system", "content": [{"type": "text", "text": SYSTEM_PROMPT}]},
            {
                "role": "user",
                "content": [
                    {"type": "video", "video": video_path},
                    {"type": "text", "text": ASSESSMENT_PROMPT_TEMPLATE.format(
                        prompt_text=prompt_text[:500],
                        duration=target_duration_sec,
                    )},
                ],
            },
        ]

        text = self.processor.apply_chat_template(
            conversation, add_generation_prompt=True, tokenize=False
        )
        audios, images, videos = process_mm_info(
            conversation, use_audio_in_video=False
        )
        inputs = self.processor(
            text=text, audio=audios, images=images, videos=videos,
            return_tensors="pt", padding=True, use_audio_in_video=False,
        )
        inputs = inputs.to(self.model.device).to(self.model.dtype)

        text_ids = self.model.generate(
            **inputs,
            return_audio=False,
            use_audio_in_video=False,
            max_new_tokens=1024,
        )
        response = self.processor.batch_decode(
            text_ids, skip_special_tokens=True, clean_up_tokenization_spaces=False
        )[0]

        return self._parse_assessment(response)

    def _parse_assessment(self, response):
        """
        Parse Qwen3-Omni's assessment response into structured results.

        Expected format (after chain-of-thought reasoning):
            ANATOMICAL: PASS — No human figures present
            TEMPORAL: PASS — Objects maintain consistent shape
            ...
            SCORE: 0.85
            VERDICT: PASS
            ISSUES: none
        """
        result = {
            "quality_score": 0.0,
            "verdict": "FAIL",
            "categories": {},
            "issues": [],
            "thinking_trace": response,
        }

        # Parse per-category results
        for cat in QUALITY_CATEGORIES:
            pattern = rf'{cat.upper()}:\s*(PASS|FAIL)\s*[—\-]\s*(.+)'
            match = re.search(pattern, response)
            if match:
                passed = match.group(1).strip() == "PASS"
                detail = match.group(2).strip()
                result["categories"][cat] = {"pass": passed, "detail": detail}
            else:
                result["categories"][cat] = {"pass": False, "detail": "Could not parse"}

        # Parse score
        score_match = re.search(r'SCORE:\s*([0-9.]+)', response)
        if score_match:
            try:
                score = float(score_match.group(1))
                result["quality_score"] = max(0.0, min(1.0, score))
            except ValueError:
                pass

        # Parse verdict
        verdict_match = re.search(r'VERDICT:\s*(PASS|MARGINAL|FAIL)', response)
        if verdict_match:
            result["verdict"] = verdict_match.group(1)
        else:
            # Derive verdict from score if not parseable
            score = result["quality_score"]
            if score >= PASS_THRESHOLD:
                result["verdict"] = "PASS"
            elif score >= MARGINAL_THRESHOLD:
                result["verdict"] = "MARGINAL"
            else:
                result["verdict"] = "FAIL"

        # Parse issues
        issues_match = re.search(r'ISSUES:\s*(.+)', response)
        if issues_match:
            issues_text = issues_match.group(1).strip()
            if issues_text.lower() != "none":
                result["issues"] = [i.strip() for i in issues_text.split(",") if i.strip()]

        return result

    def assess_all_clips(self, otio_path, clips_dir):
        """
        Assess all video clips referenced in the OTIO timeline.

        Returns list of clip assessment dicts and writes quality metadata to OTIO.
        """
        from pipeline.otio_timeline import OTIOTimeline, range_duration_sec

        import opentimelineio as otio

        otio_tl = OTIOTimeline(otio_path)
        otio_tl.load()

        # Collect all video clips from OTIO
        clip_assessments = []
        video_track = otio_tl.video_track
        total_clips = 0
        skipped = 0

        for item in video_track:
            if not isinstance(item, otio.schema.Clip):
                continue
            total_clips += 1

        log.info(f"\n{'='*60}")
        log.info(f"QUALITY CHECK — Qwen3-Omni-Thinking")
        log.info(f"{'='*60}")
        log.info(f"Total clips in OTIO: {total_clips}")
        log.info(f"Clips dir: {clips_dir}")

        assessed = 0
        for item in video_track:
            if not isinstance(item, otio.schema.Clip):
                continue

            clip_id = item.name
            scene_num = item.metadata.get("scene", 0)
            prompt_text = item.metadata.get("prompt", "")
            target_dur = range_duration_sec(item.source_range)

            # Resolve video path
            video_path = None
            if item.media_reference and hasattr(item.media_reference, "target_url"):
                ref_path = item.media_reference.target_url
                if os.path.isabs(ref_path) and os.path.exists(ref_path):
                    video_path = ref_path
                else:
                    # Try relative to clips_dir
                    candidate = os.path.join(clips_dir, os.path.basename(ref_path))
                    if os.path.exists(candidate):
                        video_path = candidate

            # Also try clips_dir/{clip_id}.mp4
            if not video_path:
                candidate = os.path.join(clips_dir, f"{clip_id}.mp4")
                if os.path.exists(candidate):
                    video_path = candidate

            if not video_path:
                log.warning(f"  [{clip_id}] Video file not found, skipping")
                skipped += 1
                continue

            assessed += 1
            log.info(f"\n[{assessed}/{total_clips}] {clip_id} (scene {scene_num}, {target_dur:.1f}s)")
            t0 = time.time()

            try:
                assessment = self.assess_clip(video_path, prompt_text, target_dur)
            except Exception as e:
                log.error(f"  Assessment failed for {clip_id}: {e}")
                assessment = {
                    "quality_score": 0.0,
                    "verdict": "FAIL",
                    "categories": {cat: {"pass": False, "detail": f"Error: {e}"} for cat in QUALITY_CATEGORIES},
                    "issues": [f"Assessment error: {e}"],
                    "thinking_trace": "",
                }

            elapsed = time.time() - t0
            log.info(f"  Score: {assessment['quality_score']:.2f} | "
                     f"Verdict: {assessment['verdict']} | {elapsed:.1f}s")

            # Write quality metadata to OTIO clip
            needs_regen = assessment["verdict"] == "FAIL"
            item.metadata["quality_score"] = assessment["quality_score"]
            item.metadata["quality_verdict"] = assessment["verdict"]
            item.metadata["quality_needs_regeneration"] = needs_regen
            item.metadata["quality_model"] = "Qwen3-Omni-30B-A3B-Thinking"
            item.metadata["quality_categories"] = assessment["categories"]
            item.metadata["quality_timestamp"] = datetime.now(timezone.utc).isoformat()

            if needs_regen:
                failed_cats = [cat for cat, v in assessment["categories"].items() if not v["pass"]]
                reason = f"Failed categories: {', '.join(failed_cats)}" if failed_cats else "Low score"
                if assessment["issues"]:
                    reason += f"; Issues: {', '.join(assessment['issues'][:3])}"
                item.metadata["quality_regeneration_reason"] = reason

            clip_assessments.append({
                "clip_id": clip_id,
                "scene": scene_num,
                "video_path": video_path,
                **assessment,
            })

        # Save OTIO with quality metadata
        otio_tl.save()
        log.info(f"\nOTIO saved with quality metadata: {otio_path}")
        log.info(f"Assessed: {assessed} | Skipped: {skipped}")

        return clip_assessments

    def generate_report(self, clip_assessments, output_path):
        """Generate quality_report.json from assessment results."""
        passed = sum(1 for c in clip_assessments if c["verdict"] == "PASS")
        marginal = sum(1 for c in clip_assessments if c["verdict"] == "MARGINAL")
        failed = sum(1 for c in clip_assessments if c["verdict"] == "FAIL")
        total = len(clip_assessments)
        avg_score = (
            sum(c["quality_score"] for c in clip_assessments) / max(1, total)
        )

        report = {
            "model": "Qwen3-Omni-30B-A3B-Thinking",
            "timestamp": datetime.now(timezone.utc).isoformat(),
            "total_clips": total,
            "passed": passed,
            "marginal": marginal,
            "failed": failed,
            "average_score": round(avg_score, 4),
            "clips": clip_assessments,
        }

        os.makedirs(os.path.dirname(output_path) or ".", exist_ok=True)
        with open(output_path, "w") as f:
            json.dump(report, f, indent=2)

        log.info(f"\nQuality report saved: {output_path}")
        log.info(f"  PASS: {passed} | MARGINAL: {marginal} | FAIL: {failed} | Avg: {avg_score:.3f}")

        return report


def get_flagged_clips(otio_path):
    """
    Read OTIO and return list of clips flagged for regeneration.

    Returns list of dicts with clip_id, scene, prompt, failed_categories,
    regeneration_reason, and enhanced_negative_prompt.
    """
    from pipeline.otio_timeline import OTIOTimeline, range_duration_sec

    import opentimelineio as otio

    otio_tl = OTIOTimeline(otio_path)
    otio_tl.load()

    flagged = []
    for item in otio_tl.video_track:
        if not isinstance(item, otio.schema.Clip):
            continue
        if not item.metadata.get("quality_needs_regeneration", False):
            continue

        clip_id = item.name
        scene_num = item.metadata.get("scene", 0)
        prompt = item.metadata.get("prompt", "")
        target_dur = range_duration_sec(item.source_range)
        categories = item.metadata.get("quality_categories", {})
        reason = item.metadata.get("quality_regeneration_reason", "")

        # Build enhanced negative prompt based on failed categories
        failed_cats = [cat for cat, v in categories.items() if not v.get("pass", True)]
        extra_negatives = []
        for cat in failed_cats:
            if cat in REGENERATION_NEGATIVE_PROMPTS:
                extra_negatives.append(REGENERATION_NEGATIVE_PROMPTS[cat])

        flagged.append({
            "clip_id": clip_id,
            "scene_number": scene_num,
            "prompt": prompt,
            "target_duration_sec": target_dur,
            "failed_categories": failed_cats,
            "regeneration_reason": reason,
            "enhanced_negative_prompt": ", ".join(extra_negatives) if extra_negatives else "",
        })

    return flagged


def main():
    """CLI entry point for quality checking on QC VM."""
    parser = argparse.ArgumentParser(
        description="Video Quality Checker — Qwen3-Omni-Thinking",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  python3 -m pipeline.quality_checker \\
      --otio production/timeline.otio \\
      --clips-dir /workspace/outputs \\
      --output production/quality_report.json
        """,
    )
    parser.add_argument("--otio", required=True, help="Path to .otio timeline file")
    parser.add_argument("--clips-dir", required=True, help="Directory containing video clips")
    parser.add_argument("--output", required=True, help="Path for quality_report.json output")
    parser.add_argument("--model-path", default=None, help=f"Model path (default: {QWEN_LOCAL_PATH})")
    parser.add_argument("--gpu", type=int, default=None, help="GPU index")

    args = parser.parse_args()

    if args.gpu is not None:
        os.environ["CUDA_VISIBLE_DEVICES"] = str(args.gpu)

    checker = VideoQualityChecker(model_path=args.model_path)
    checker.load_model()

    assessments = checker.assess_all_clips(args.otio, args.clips_dir)
    checker.generate_report(assessments, args.output)


if __name__ == "__main__":
    main()
