"""
Pydantic models for the planning-heavy production orchestrator.

Defines the data structures for production plans, clip tasks, batch results,
and the evaluate-optimize loop used to refine plans before GPU execution.
"""

from __future__ import annotations

from enum import IntEnum
from typing import Optional

from pydantic import BaseModel, Field


# ---------------------------------------------------------------------------
# Quality rating (mirrors mcp-agent's EvaluatorOptimizer QualityRating)
# ---------------------------------------------------------------------------

class QualityRating(IntEnum):
    """Plan quality rating from the evaluator LLM."""
    POOR = 0       # Major issues — duration violations, missing clips
    FAIR = 1       # Several improvements needed
    GOOD = 2       # Minor improvements possible
    EXCELLENT = 3  # No improvements needed — ready for execution


# ---------------------------------------------------------------------------
# Plan models
# ---------------------------------------------------------------------------

class ClipTask(BaseModel):
    """A single video clip generation task."""
    clip_id: str = Field(
        description="Unique clip identifier, e.g. 's001_p002'",
    )
    scene_num: int = Field(description="Scene number")
    phrase_idx: int = Field(description="Phrase index within scene")
    prompt: str = Field(description="Visual description prompt for LTX-2.3")
    negative_prompt: str = Field(
        default="",
        description="Negative prompt (from visual_style.avoid)",
    )
    duration: float = Field(
        description="Target duration in seconds (max 10.0, LTX-2.3 limit)",
        le=10.0,
    )
    lora_id: str = Field(
        default="documentary-realism",
        description="LoRA style identifier",
    )
    lora_weight: float = Field(
        default=0.75,
        description="LoRA weight (0.0-1.0)",
    )
    assigned_worker: str = Field(
        default="auto",
        description="Worker URL or 'auto' for round-robin assignment",
    )
    priority: int = Field(
        default=0,
        description="Higher = generate first (style-reference clips get higher priority)",
    )
    style_group: str = Field(
        default="default",
        description="Coherence grouping — clips in the same group share visual style",
    )
    skip: bool = Field(
        default=False,
        description="True if this clip already exists with good QA (resume support)",
    )


class ClipBatch(BaseModel):
    """A batch of clips to be generated in parallel."""
    description: str = Field(description="Human-readable batch description")
    tasks: list[ClipTask] = Field(description="Clips in this batch")
    rationale: str = Field(
        default="",
        description="Why these clips are grouped together (style coherence, dependencies)",
    )


class ProductionPlan(BaseModel):
    """Full production plan generated by the optimizer LLM."""
    batches: list[ClipBatch] = Field(description="Ordered list of clip batches")
    is_complete: bool = Field(
        default=True,
        description="Whether this plan covers all visual concepts",
    )
    strategy: str = Field(
        default="",
        description="High-level strategy description",
    )
    worker_assignment: dict[str, list[str]] = Field(
        default_factory=dict,
        description="Mapping of worker URL -> list of clip_ids assigned",
    )
    estimated_gpu_minutes: float = Field(
        default=0.0,
        description="Estimated total GPU time in minutes",
    )
    risk_assessment: str = Field(
        default="",
        description="Identified risks and mitigation strategies",
    )


# ---------------------------------------------------------------------------
# Evaluation result
# ---------------------------------------------------------------------------

class PlanEvaluation(BaseModel):
    """Result of evaluating a production plan."""
    rating: QualityRating = Field(description="Quality rating of the plan")
    feedback: str = Field(
        description="Specific feedback and suggestions for improvement",
    )
    needs_improvement: bool = Field(
        description="Whether the plan needs further refinement",
    )
    focus_areas: list[str] = Field(
        default_factory=list,
        description="Specific areas to focus on in next iteration",
    )


# ---------------------------------------------------------------------------
# Plan verification
# ---------------------------------------------------------------------------

class PlanVerificationError(BaseModel):
    """A single verification error."""
    category: str = Field(description="Error category (e.g. 'duration_violation')")
    message: str = Field(description="Human-readable error description")
    clip_id: Optional[str] = Field(default=None, description="Affected clip ID")
    details: dict = Field(default_factory=dict, description="Additional context")


class PlanVerificationResult(BaseModel):
    """Result of structural plan verification (hard gate)."""
    is_valid: bool = Field(default=True, description="Whether the plan passed all checks")
    errors: list[PlanVerificationError] = Field(
        default_factory=list,
        description="List of verification errors",
    )
    warnings: list[str] = Field(
        default_factory=list,
        description="Non-blocking warnings",
    )

    def add_error(
        self,
        category: str,
        message: str,
        clip_id: Optional[str] = None,
        details: Optional[dict] = None,
    ) -> None:
        """Add a verification error and mark the result as invalid."""
        self.is_valid = False
        self.errors.append(PlanVerificationError(
            category=category,
            message=message,
            clip_id=clip_id,
            details=details or {},
        ))

    def format_errors(self) -> str:
        """Format all errors as a human-readable string."""
        parts = []
        for err in self.errors:
            clip_str = f" (clip {err.clip_id})" if err.clip_id else ""
            parts.append(f"[{err.category}]{clip_str}: {err.message}")
        return "; ".join(parts)


# ---------------------------------------------------------------------------
# Execution results
# ---------------------------------------------------------------------------

class ClipResult(BaseModel):
    """Result of generating a single video clip."""
    clip_id: str = Field(description="Clip identifier")
    status: str = Field(
        description="Generation status: 'generated', 'skipped', 'failed'",
    )
    qa_quality: str = Field(default="unknown", description="QA quality rating")
    qa_reason: str = Field(default="", description="QA reason text")
    output_path: str = Field(default="", description="Path to generated MP4")
    actual_duration: float = Field(default=0.0, description="Actual clip duration")
    gen_time: float = Field(default=0.0, description="GPU generation time in seconds")
    error: str = Field(default="", description="Error message if failed")
    scene_num: int = Field(default=0, description="Scene number")
    phrase_idx: int = Field(default=0, description="Phrase index")
    lora_id: str = Field(default="", description="LoRA used")


class BatchResult(BaseModel):
    """Result of executing a single batch."""
    batch_idx: int = Field(description="Batch index in the plan")
    clip_results: list[ClipResult] = Field(
        default_factory=list,
        description="Results for each clip in the batch",
    )
    failed_clips: list[str] = Field(
        default_factory=list,
        description="Clip IDs that failed",
    )
    avg_qa_score: float = Field(default=0.0, description="Average QA score")

    def compute_stats(self) -> None:
        """Compute failed_clips and avg_qa_score from clip_results."""
        self.failed_clips = [
            cr.clip_id for cr in self.clip_results if cr.status == "failed"
        ]
        qa_scores = []
        for cr in self.clip_results:
            if cr.qa_quality == "excellent":
                qa_scores.append(1.0)
            elif cr.qa_quality == "good":
                qa_scores.append(0.75)
            elif cr.qa_quality == "fair":
                qa_scores.append(0.5)
            elif cr.qa_quality in ("poor", "rejected"):
                qa_scores.append(0.0)
        self.avg_qa_score = sum(qa_scores) / max(len(qa_scores), 1)


class ProductionPlanResult(BaseModel):
    """Full result of executing a production plan."""
    plan: ProductionPlan = Field(description="The executed plan")
    batch_results: list[BatchResult] = Field(
        default_factory=list,
        description="Results for each batch",
    )
    total_clips: int = Field(default=0, description="Total clips processed")
    failed_clips: int = Field(default=0, description="Number of failed clips")
    skipped_clips: int = Field(default=0, description="Number of skipped clips")
    replan_count: int = Field(default=0, description="Number of replanning events")
