"""Pydantic models for DeepSeek-generated feature plans."""

from __future__ import annotations

from pydantic import BaseModel, Field


class FeaturePlan(BaseModel):
    """A structured feature plan generated by DeepSeek v4-flash."""

    title: str = Field(description="Short title for the feature")
    problem: str = Field(description="What user-visible problem this fixes")
    root_cause: str = Field(
        description="Technical root cause, referencing specific files/functions"
    )
    fix_description: str = Field(
        description="Detailed fix description with implementation steps"
    )
    files_to_modify: list[str] = Field(
        default_factory=list,
        description="List of file paths that need changes",
    )
    estimated_effort: str = Field(
        description="One of: small, medium, large",
        pattern=r"^(small|medium|large)$",
    )
